name: CI Pipeline with Vulnerability Scanning

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      SEVERITY_THRESHOLD: ${{ secrets.VULNERABILITY_SEVERITY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp .

      - name: Run Trivy scan
        id: trivy
        uses: aquasecurity/trivy-action@latest  # Use 'latest' or specify a version like 'v0.30.0'
        with:
          image-ref: myapp
          format: 'json'
          output: 'trivy-report.json'
          severity: ${{ env.SEVERITY_THRESHOLD }}

      - name: Upload Trivy report (if scan ran)
        if: steps.trivy.outcome != 'skipped'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

      - name: Provide feedback on vulnerabilities
        run: |
          if [ -f trivy-report.json ]; then
            if jq -e '.[] | select(.Severity=="CRITICAL" or .Severity=="HIGH")' trivy-report.json > /dev/null; then
              echo "Critical or High vulnerabilities found. Build failed."
              exit 1
            else
              echo "No critical or high vulnerabilities found. Build passed."
            fi
          else
            echo "Trivy report not found. Assuming no vulnerabilities."
          fi
