name: CI Pipeline with Vulnerability Scanning

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      SEVERITY_THRESHOLD: ${{ secrets.VULNERABILITY_SEVERITY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Latest Trivy (Vulnerability Scanner)
        run: |
          set -e
          curl -sSfL https://aquasecurity.github.io/trivy/install.sh | sh -s -- -b /usr/local/bin

      - name: Add /usr/local/bin to PATH
        run: echo "PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV

      - name: Verify Trivy Installation
        run: |
          set -e
          trivy --version

      - name: Build Docker image
        run: |
          set -e
          docker build -t myapp .

      - name: Run Trivy scan
        id: trivy
        run: |
          set -e
          trivy image --exit-code 1 --format json --output trivy-report.json --severity $SEVERITY_THRESHOLD myapp

      - name: List files in the directory (for debugging)
        run: |
          ls -alh

      - name: Upload Trivy report (if scan ran)
        if: steps.trivy.outcome != 'skipped'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

      - name: Provide feedback on vulnerabilities
        run: |
          set -e
          if [ -f trivy-report.json ]; then
            if jq -e '.[] | select(.Severity=="CRITICAL" or .Severity=="HIGH")' trivy-report.json > /dev/null; then
              echo "Critical or High vulnerabilities found. Build failed."
              exit 1
            else
              echo "No critical or high vulnerabilities found. Build passed."
            fi
          else
            echo "Trivy report not found. Assuming no vulnerabilities."
          fi
