name: CI Pipeline with Vulnerability Scanning

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      SEVERITY_THRESHOLD: ${{ secrets.VULNERABILITY_SEVERITY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use a specific commit SHA or tag for stability

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Trivy (Vulnerability Scanner)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.29.0/trivy_0.29.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.29.0_Linux-64bit.deb
      - name: Build Docker image
        run: |
          docker build -t myapp .
      - name: Run Trivy scan
        id: trivy
        run: trivy image --exit-code 0 --format json --output trivy-report.json --severity $SEVERITY_THRESHOLD myapp

      - name: List files in the directory (for debugging)
        run: |
          ls -alh
      - name: Upload Trivy report (if scan ran)
        if: steps.trivy.outcome != 'skipped'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

      - name: Provide feedback on vulnerabilities
        run: |
          if [ -f trivy-report.json ]; then
            if jq -e '.[] | select(.Severity=="CRITICAL" or .Severity=="HIGH")' trivy-report.json > /dev/null; then
              echo "Critical or High vulnerabilities found. Build failed."
              exit 1
            else
              echo "No critical or high vulnerabilities found. Build passed."
            fi
          else
            echo "Trivy report not found. Assuming no vulnerabilities."
          fi
