name: CI Pipeline with Vulnerability Scanning

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      SEVERITY_THRESHOLD: ${{ secrets.VULNERABILITY_SEVERITY || 'CRITICAL,HIGH' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.29.0/trivy_0.29.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.29.0_Linux-64bit.deb

      - name: Build Docker image
        run: |
          docker build -t myapp .

      - name: Run Trivy scan
        id: trivy
        run: |
          trivy image --exit-code 0 --format json --output trivy-report.json --severity $SEVERITY_THRESHOLD myapp || true

      - name: List files in the directory
        run: |
          ls -alh

      - name: Upload Trivy report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.json

      - name: Check vulnerabilities
        run: |
          if [ -f trivy-report.json ]; then
            if grep -q '"Vulnerabilities":' trivy-report.json; then
              echo "::error::Vulnerabilities found!"
              exit 1
            else
              echo "No vulnerabilities found"
            fi
          else
            echo "::error::Trivy report missing"
            exit 1
          fi
